# Generated by Django 5.2.17 on 2026-09-18 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models

def fill_payment_keys(apps, schema_editor):
    for order in apps.get_model('shop','Order').objects.all().iterator():
        order.payment_key = uuid.uuid4()
        order.save(update_fields=['payment_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_url', models.URLField(blank=True)),
                ('ghala_token', models.TextField(blank=True)),
                ('ghala_secret', models.TextField(blank=True)),
                ('ghala_subscription', models.CharField(blank=True, max_length=150)),
                ('ghala_map', models.JSONField(blank=True, default=dict)),
                ('mapping_confirmed', models.BooleanField(default=False)),
                ('snippe_token', models.TextField(blank=True)),
                ('snippe_secret', models.TextField(blank=True)),
                ('openai_key', models.TextField(blank=True)),
                ('agent_name', models.CharField(default='Duka Assistant', max_length=80)),
                ('agent_policies', models.TextField(blank=True, max_length=6000)),
                ('agent_enabled', models.BooleanField(default=False)),
                ('ghala_auto_reply_disabled', models.BooleanField(default=False)),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=80)),
                ('worker_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('available_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('delivery_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='quote',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(default='saved', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(fill_payment_keys,migrations.RunPython.noop),
        migrations.AlterField(model_name='order',name='payment_key',field=models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('shop', 'phone'), name='unique_shop_phone'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('conversation', 'external_id'), name='unique_conversation_external_message'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('origin_key', ''), _negated=True), fields=('shop', 'origin_key'), name='unique_order_origin'),
        ),
        migrations.AddField(
            model_name='connection',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='job',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('shop', 'provider', 'delivery_id'), name='unique_provider_delivery'),
        ),
    ]
