# Generated by Django 5.2.17 on 2026-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_backfill_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('ready_for_delivery', 'Ready for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='unfulfilled', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending payment', 'Pending payment'), ('Paid', 'Paid'), ('Ready for delivery', 'Ready for delivery'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Pending payment', max_length=32),
        ),
    ]
