# Generated by Django 5.2.17 on 2026-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_otpcode_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=16),
        ),
    ]
