# Generated by Django 5.2.17 on 2026-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_otp_sms_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='connection',
            name='meta_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_phone_number_id', ''), _negated=True), fields=('meta_phone_number_id',), name='unique_meta_phone_number_id'),
        ),
    ]
